<?php

namespace Alaaeta\Translation\Tests;

use Alaaeta\Translation\TranslationServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }


    protected function getPackageProviders($app)
    {
        return [
          TranslationServiceProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'translationdb');
        $app['config']->set('database.connections.translationdb', [
            'driver' => 'sqlite',
            'database' => ':memory:'
        ]);
    }

}
